language: ruby
sudo: false
rvm:
  - 2.1.0
  - 2.2
  - 2.3.1
deploy:
  provider: rubygems
  api_key:
    secure: Xjq+v+jEU6wK4BtyfnV1elegNcxK6Ah/O99Sn9c2IlkCmJ1wxLBouqzEiSorSJ4IOMa5H2y3gwo5GXOr6Y7d8huyGrPuBeCSGqAmH77wNCIv7G+jnLiYb1sRZbtKcPW2QaN6JF81qDIelwyspMfo6/ug1qN1x323UaxZl7f7nUE=
  gem: babelish
  on:
    tags: true
    repo: rbrovko/babelish_rnc
    all_branches: true
